WIP - Add ssh-key to be able to access private repositories

diff --git a/.github/workflows/terraform_apply.yaml b/.github/workflows/terraform_apply.yaml
--- a/.github/workflows/terraform_apply.yaml
+++ b/.github/workflows/terraform_apply.yaml
@@ -10,17 +10,67 @@ on:
         required: false
         type: string
         default: "canonical/webteam-terraform-plans"
+      vault_model_name:
+        required: false
+        type: string
     secrets:
       VAULT_APPROLE_ROLE_ID:
         required: true
       VAULT_APPROLE_SECRET_ID:
         required: true
+      TERRAFORM_REPO_SSH_KEY:
+        required: false
 
 jobs:
+  validate:
+    name: Validation
+    runs-on: ubuntu-latest
+    outputs:
+      vault_model: ${{ steps.validate_vault.outputs.vault_model }}
+      TERRAFORM_REPO_SSH_KEY: ${{ steps.validate_key.outputs.TERRAFORM_REPO_SSH_KEY }}
+    steps:
+      - name: Validate vault_model_name
+        id: validate_vault
+        run: |
+          if [ -n "${{ inputs.vault_model_name }}" ]; then
+            # input provided
+            echo "vault_model=${{ inputs.vault_model_name }}" >> $GITHUB_OUTPUT
+          else
+            # get last part of the path, which contains the model name if the default folder
+            # structure of webteam-terraform-plans is followed
+            VAULT_MODEL=$(basename ${{ inputs.terraform_dir }})
+
+            if [ ! -n "$VAULT_MODEL" ]; then
+              echo "Could not infer vault model name. Please provide it as input."
+              exit 1
+            else
+              echo "vault_model=$VAULT_MODEL" >> $GITHUB_OUTPUT
+          fi
+      
+      - name: Validate ssh-key secret
+        id: validate_key
+        env:
+          VAULT_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
+          VAULT_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
+          VAULT_ADDR: https://vault.ps7.admin.canonical.com
+        run: |
+          # if the token is already present then skip Vault auth
+          if ! vault token lookup 1>/dev/null 2>&1; then
+            echo "Authenticating to $VAULT_ADDR with AppRole"
+            vault write -f -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID" | vault login -no-print -
+          fi
+
+          if [ -n "${{ secrets.TERRAFORM_REPO_SSH_KEY }}" ]; then
+            # secret provided
+            echo "TERRAFORM_REPO_SSH_KEY=${{ secrets.TERRAFORM_REPO_SSH_KEY }}" >> $GITHUB_OUTPUT
+          else
+            echo "TERRAFORM_REPO_SSH_KEY=$(vault kv get -field=ssh-key secret/groups/canonical-webdesign-marketplace/webteam_terraform_plans)" >> $GITHUB_OUTPUT
+
   deploy:
     name: Terraform Apply
     if: always() && !failure() && !cancelled()
     runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
+    needs: [validate]
     steps:
       - name: Install Dependencies
         run: |
@@ -30,17 +80,34 @@ jobs:
         uses: actions/checkout@v7
         with:
           repository: ${{ inputs.terraform_github_repo }}
+          ssh-key: ${{ needs.validate.outputs.TERRAFORM_REPO_SSH_KEY }}
 
       - uses: hashicorp/setup-terraform@v4
         with:
           terraform_wrapper: false
-
-      - name: Terraform init and apply
+      
+      - name: Get S3 backend creds
         env:
           VAULT_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
           VAULT_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
+          VAULT_ADDR: https://vault.ps7.admin.canonical.com
+          VAULT_MODEL: ${{ needs.validate.outputs.vault_model }}
         run: |
-          # authenticate to vault
-          source ./${{ inputs.terraform_dir }}/s3_credentials_jaas.sh
-          terraform -chdir=${{ inputs.terraform_dir }} init
-          terraform -chdir=${{ inputs.terraform_dir }} apply -auto-approve
+          # if the token is already present then skip Vault auth
+          if ! vault token lookup 1>/dev/null 2>&1; then
+            echo "Authenticating to $VAULT_ADDR with AppRole"
+            vault write -f -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID" | vault login -no-print -
+          fi
+
+          # retrieve the S3 creds through Vault
+          AWS_ACCESS_KEY_ID=$(vault kv get -field=access_key secret/services/"$VAULT_MODEL"/s3) || return 0
+          AWS_SECRET_ACCESS_KEY=$(vault kv get -field=secret_key secret/services/"$VAULT_MODEL"/s3) || return 0
+          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
+          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
+          echo "Backend credentials set for $VAULT_MODEL in cloud ps7"
+
+      - name: Terraform init and apply
+        run: |
+          #terraform -chdir=${{ inputs.terraform_dir }} init
+          #terraform -chdir=${{ inputs.terraform_dir }} apply -auto-approve
+          echo "Deploying..."
